import type { Language, LocalizedTextSet } from '@/types/app';

export const texts: Record<Language, LocalizedTextSet> = {
  ja: {
    title: 'わかるまで',
    subtitle: '算数文章題アプリ',
    takePhoto: '写真をとる',
    loadingConverting: 'HEIC画像を変換中…',
    loadingProcessing: 'プリント読み込み中…',
    errorNoFile: 'ファイルが選択されていません。',
    errorConversion: 'ごめんね、しゃしんの変換に失敗しました。別の形式で試してみてね。',
    errorOcr: 'ごめんね、プリントから問題を見つけられなかったみたい。別のしゃしんで試してみてね。',
    selectProblem: 'もんだいを選びましょう',
    selectPhoto: '写真を選ぶ',
    reset: 'はじめからやり直す',
    messagePlaceholder: '先生へのメッセージ',
    selectDifferentProblem: '← 別の問題を選ぶ',
    resetRight: 'はじめからやり直す →',
    thinking: '先生が考え中…',
    communicationError: 'ごめんなさい、通信がうまくいかなかったようです。',
    restoringSession: '保存した会話を読み込んでいます…',
    generatingSimilar: '類題を作成中…',
    similarError: 'ごめんなさい、類題をうまく作れませんでした。',
    speechNotSupported: 'ごめんなさい、お使いのブラウザは音声入力に対応していません。',
    speechError: '音声の聞き取りに失敗しました。',
    initialMessage: 'この問題について教えてください。',
    similarProblemButton: '似た問題にチャレンジ！',
    savedProblem: '保存した問題を再開します。',
    personalizedMessage:
      '🌟 すごいね、ここまでよく考えたね！\n\nつぎのもんだいでは\n「どの計算かな？」を見つけるのがポイントだよ✨\n\n類題でもっと得意になろう！',
  },
  en: {
    title: 'Until You Understand/WAKARUMADE',
    subtitle: 'Math Word Problems for Kids',
    takePhoto: 'Take a Photo',
    loadingConverting: 'Converting HEIC image...',
    loadingProcessing: 'Reading worksheet...',
    errorNoFile: 'No file selected.',
    errorConversion: 'Sorry, image conversion failed. Please try another format.',
    errorOcr: "Sorry, couldn't find problems in the worksheet. Please try another image.",
    selectProblem: 'Choose a problem',
    selectPhoto: 'Select a photo',
    reset: 'Start over',
    messagePlaceholder: 'Message to teacher',
    selectDifferentProblem: '← Choose another problem',
    resetRight: 'Start over →',
    thinking: 'Teacher is thinking...',
    communicationError: 'Sorry, there was a communication error.',
    restoringSession: 'Loading saved conversation...',
    generatingSimilar: 'Generating similar problem...',
    similarError: "Sorry, couldn't generate a similar problem.",
    speechNotSupported: "Sorry, your browser doesn't support voice input.",
    speechError: 'Failed to recognize speech.',
    initialMessage: 'Please teach me about this problem.',
    similarProblemButton: 'Try a similar problem!',
    savedProblem: 'Resume saved problem.',
    personalizedMessage:
      '🌟 Great job! You thought really hard!\n\nFor the next problem,\nfind out "which calculation?" is the key! ✨\n\nLet\'s become even better with similar problems!',
  },
};
